// 
// Decompiled by Procyon v0.5.36
// 

package com.salhack.summit.main;

import com.salhack.summit.gui.hud.items.SelectorMenuComponent;
import com.salhack.summit.gui.hud.items.ArrayListComponent;
import com.salhack.summit.module.combat.Offhand;
import com.salhack.summit.module.render.ItemPhysics;
import com.salhack.summit.module.render.NoRender;
import com.salhack.summit.module.world.NoGlitchBlocks;
import com.salhack.summit.module.movement.Blink;
import com.salhack.summit.module.movement.BoatFly;
import com.salhack.summit.module.movement.ElytraFly;
import com.salhack.summit.module.exploit.Reach;
import com.salhack.summit.module.movement.NoRotate;
import com.salhack.summit.module.exploit.PacketFly;
import com.salhack.summit.module.render.ViewClip;
import com.salhack.summit.module.ui.Hud;
import com.salhack.summit.module.world.StashLogger;
import com.salhack.summit.module.movement.NoSlow;
import com.salhack.summit.module.exploit.LiquidInteract;
import com.salhack.summit.module.misc.Friends;
import com.salhack.summit.module.misc.StopWatch;
import com.salhack.summit.module.exploit.PacketCanceller;
import com.salhack.summit.module.ui.Colors;
import com.salhack.summit.module.ui.ClickGui;
import com.salhack.summit.module.misc.ChestStealer;
import com.salhack.summit.module.exploit.EntityDesync;
import com.salhack.summit.module.world.AutoTunnel;
import com.salhack.summit.module.bot.DupeBot;
import com.salhack.summit.module.misc.AutoReconnect;
import com.salhack.summit.module.misc.DiscordRPC;
import com.salhack.summit.module.render.Freecam;
import com.salhack.summit.module.movement.Flight;
import com.salhack.summit.module.world.TimerModule;
import com.salhack.summit.module.combat.HoleFiller;
import com.salhack.summit.module.misc.AutoMendArmor;
import com.salhack.summit.module.combat.AutoCity;
import com.salhack.summit.module.ui.Keybinds;
import com.salhack.summit.module.combat.SelfTrap;
import com.salhack.summit.module.combat.AutoTrapFeet;
import com.salhack.summit.module.combat.AutoTrap;
import com.salhack.summit.module.combat.Surround;
import com.salhack.summit.module.combat.AutoCrystal;
import com.salhack.summit.module.combat.Aura;
import com.salhack.summit.module.combat.AutoTotem;
import com.salhack.summit.module.movement.AutoWalk;
import com.salhack.summit.module.misc.ChorusFruitBypass;
import com.salhack.summit.module.misc.ChatModifications;
import com.salhack.summit.module.render.StorageESP;
import com.salhack.summit.module.render.EntityESP;
import com.salhack.summit.module.render.Wallhack;
import com.salhack.summit.module.combat.AutoArmor;
import com.salhack.summit.module.misc.AntiAFK;

public class SummitStatic
{
    public static AntiAFK ANTIAFK;
    public static AutoArmor AUTOARMOR;
    public static Wallhack WALLHACK;
    public static EntityESP ENTITYESP;
    public static StorageESP STORAGEESP;
    public static ChatModifications CHATMODIFICATIONS;
    public static ChorusFruitBypass CHORUSFRUITBYPASS;
    public static AutoWalk AUTOWALK;
    public static AutoTotem AUTOTOTEM;
    public static Aura AURA;
    public static AutoCrystal AUTOCRYSTAL;
    public static Surround SURROUND;
    public static AutoTrap AUTOTRAP;
    public static AutoTrapFeet AUTOTRAPFEET;
    public static SelfTrap SELFTRAP;
    public static Keybinds KEYBINDS;
    public static AutoCity AUTOCITY;
    public static AutoMendArmor AUTOMEND;
    public static HoleFiller HOLEFILLER;
    public static TimerModule TIMER;
    public static Flight FLIGHT;
    public static Freecam FREECAM;
    public static DiscordRPC DISCORDRPC;
    public static AutoReconnect AUTORECONNECT;
    public static DupeBot DUPEBOT;
    public static AutoTunnel AUTOTUNNEL;
    public static EntityDesync ENTITYDESYNC;
    public static ChestStealer CHESTSTEALER;
    public static ClickGui CLICKGUI;
    public static Colors COLORS;
    public static PacketCanceller PACKETCANCELLER;
    public static StopWatch STOPWATCH;
    public static Friends FRIENDS;
    public static LiquidInteract LIQUIDINTERACT;
    public static NoSlow NOSLOW;
    public static StashLogger STASHLOGGER;
    public static Hud HUD;
    public static ViewClip VIEWCLIP;
    public static PacketFly PACKETFLY;
    public static NoRotate NOROTATE;
    public static Reach REACH;
    public static ElytraFly ELYTRAFLY;
    public static BoatFly BOATFLY;
    public static Blink BLINK;
    public static NoGlitchBlocks NOGLITCHBLOCKS;
    public static NoRender NORENDER;
    public static ItemPhysics ITEMPHYSICS;
    public static Offhand OFFHAND;
    public static ArrayListComponent ARRAYLIST;
    public static SelectorMenuComponent SELECTORMENU;
}
